stages:
  - dependencies
  - test
  - build

install_dependencies:
  image: composer/composer:2.0.6
  stage: dependencies
  script:
    - cd back
    - composer update
    - composer install

test:
  image: composer/composer:2.0.6
  stage: test
  script:
    - cd back
    - composer update
    - composer install
    - cp .env.example .env
    - ./vendor/bin/phpunit

build_image_back:
  image: composer/composer:2.0.6
  stage: build
  script:
    - cd back
    - composer update
    - composer install
    - cp .env.example .env
  artifacts:
    paths:
      - back